[package]
name = "sokoban"
version = "0.1.0"
authors = ["BittersweetPuff"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0"